<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE editorial [

        <!ELEMENT editorial (informe)*>
        <!ELEMENT informe (Nombre_editorial?, descripcion?, fecha, datos)>

        <!ELEMENT datos (ventas)*>

        <!ATTLIST ventas region (Norte | Centro | Sur) #REQUIRED>
        <!ATTLIST ventas trimestre (1 | 2 | 3 | 4) #REQUIRED>
        <!ATTLIST ventas libros_vendidos CDATA "NO_INFO">


        <!ELEMENT ventas ANY>
        <!ELEMENT libros_vendidos ANY>
        <!ELEMENT Nombre_editorial (#PCDATA)>
        <!ELEMENT descripcion (#PCDATA)>
        <!ELEMENT fecha (#PCDATA)>

        ]>

<editorial>

    <informe>

        <Nombre_editorial>Ediciones Aranda</Nombre_editorial>
        <descripcion>Informe de ventas para las regiones Norte, Centro y Sur</descripcion>
        <fecha>30/09/2021</fecha>

        <datos>
            <ventas region="Norte" trimestre="1" libros_vendidos="24000"/>
            <ventas region="Norte" trimestre="2" libros_vendidos="38600"/>
            <ventas region="Norte" trimestre="3" libros_vendidos="NO_INFO"/>
            <ventas region="Norte" trimestre="4" libros_vendidos="NO_INFO"/>

            <ventas region="Centro" trimestre="1" libros_vendidos="NO_INFO"/>
            <ventas region="Centro" trimestre="2" libros_vendidos="16080"/>
            <ventas region="Centro" trimestre="3" libros_vendidos="25080"/>
            <ventas region="Centro" trimestre="4" libros_vendidos="29080"/>

            <ventas region="Sur" trimestre="1" libros_vendidos="27000"/>
            <ventas region="Sur" trimestre="2" libros_vendidos="31400"/>
            <ventas region="Sur" trimestre="3" libros_vendidos="40100"/>
            <ventas region="Sur" trimestre="4" libros_vendidos="30000"/>
        </datos>

    </informe>

</editorial>